# Generated by Django 5.1.7 on 2025-03-23 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pyqs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='core.course')),
            ],
        ),
    ]
